name: linq
description: Linq for dart
version: 1.0.0
homepage: https://github.com/SahandAkbarzadeh/linq_dart
author: Sahandevs <sahandevs@gmail.com>

environment:
  sdk: ">=2.6.0-dev.6.0 <3.0.0"

dev_dependencies:
  test: ^1.0.0
  build_runner: ^1.0.0
  code_gen:
    path: ../tool/codegen
